### ISSUE TITLE
Weird error: end not defined for VCABM algorithm

### ISSUE THREAD

**Issue by shipengcheng1230** [SciML/OrdinaryDiffEq.jl#1410] opened 2021-05-21 02:45 UTC
Hi, consider the following MWE:
```julia
julia> using OrdinaryDiffEq

julia> function lorenz(du,u,p,t)
        du[1] = 10.0(u[2]-u[1])
        du[2] = u[1]*(28.0-u[3]) - u[2]
        du[3] = u[1]*u[2] - (8/3)*u[3]
       end
lorenz (generic function with 1 method)

julia> u0 = [1.0;0.0;0.0]
3-element Vector{Float64}:
 1.0
 0.0
 0.0

julia> tspan = (0.0,100.0)
(0.0, 100.0)

julia> prob = ODEProblem(lorenz,u0,tspan)
ODEProblem with uType Vector{Float64} and tType Float64. In-place: true
timespan: (0.0, 100.0)
u0: 3-element Vector{Float64}:
 1.0
 0.0
 0.0

julia> sol = solve(prob,Tsit5());

julia> sol = solve(prob,VCABM5());
ERROR: UndefVarError: end not defined
Stacktrace:
  [1] perform_step!(integrator::OrdinaryDiffEq.ODEIntegrator{VCABM5, true, Vector{Float64}, Nothing, Float64, SciMLBase.NullParameters, Float64, Float64, Float64, Vector{Vector{Float64}}, ODESolution{Float64, 2, Vector{Vector{Float64}}, Nothing, Nothing, Vector{Float64}, Vector{Vector{Vector{Float64}}}, ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, typeof(lorenz), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, VCABM5, OrdinaryDiffEq.InterpolationData{ODEFunction{true, typeof(lorenz), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Vector{Vector{Float64}}, Vector{Float64}, Vector{Vector{Vector{Float64}}}, OrdinaryDiffEq.VCABM5Cache{Vector{Float64}, Vector{Float64}, OrdinaryDiffEq.RK4Cache{Vector{Float64}, Vector{Float64}, Vector{Float64}}, Vector{Float64}, Matrix{Float64}, Vector{Float64}, Vector{Vector{Float64}}, Vector{Float64}}}, DiffEqBase.DEStats}, ODEFunction{true, typeof(lorenz), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, OrdinaryDiffEq.VCABM5Cache{Vector{Float64}, Vector{Float64}, OrdinaryDiffEq.RK4Cache{Vector{Float64}, Vector{Float64}, Vector{Float64}}, Vector{Float64}, Matrix{Float64}, Vector{Float64}, Vector{Vector{Float64}}, Vector{Float64}}, OrdinaryDiffEq.DEOptions{Float64, Float64, Float64, Float64, PIController{Rational{Int64}}, typeof(DiffEqBase.ODE_DEFAULT_NORM), typeof(LinearAlgebra.opnorm), Nothing, CallbackSet{Tuple{}, Tuple{}}, typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), DataStructures.BinaryMinHeap{Float64}, DataStructures.BinaryMinHeap{Float64}, Nothing, Nothing, Int64, Tuple{}, Tuple{}, Tuple{}}, Vector{Float64}, Float64, Nothing, OrdinaryDiffEq.DefaultInit}, cache::OrdinaryDiffEq.VCABM5Cache{Vector{Float64}, Vector{Float64}, OrdinaryDiffEq.RK4Cache{Vector{Float64}, Vector{Float64}, Vector{Float64}}, Vector{Float64}, Matrix{Float64}, Vector{Float64}, Vector{Vector{Float64}}, Vector{Float64}}, repeat_step::Bool)
    @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/WZTwh/src/perform_step/adams_bashforth_moulton_perform_step.jl:1319
  [2] perform_step!
    @ ~/.julia/packages/OrdinaryDiffEq/WZTwh/src/perform_step/adams_bashforth_moulton_perform_step.jl:1269 [inlined]
  [3] solve!(integrator::OrdinaryDiffEq.ODEIntegrator{VCABM5, true, Vector{Float64}, Nothing, Float64, SciMLBase.NullParameters, Float64, Float64, Float64, Vector{Vector{Float64}}, ODESolution{Float64, 2, Vector{Vector{Float64}}, Nothing, Nothing, Vector{Float64}, Vector{Vector{Vector{Float64}}}, ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, typeof(lorenz), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, VCABM5, OrdinaryDiffEq.InterpolationData{ODEFunction{true, typeof(lorenz), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Vector{Vector{Float64}}, Vector{Float64}, Vector{Vector{Vector{Float64}}}, OrdinaryDiffEq.VCABM5Cache{Vector{Float64}, Vector{Float64}, OrdinaryDiffEq.RK4Cache{Vector{Float64}, Vector{Float64}, Vector{Float64}}, Vector{Float64}, Matrix{Float64}, Vector{Float64}, Vector{Vector{Float64}}, Vector{Float64}}}, DiffEqBase.DEStats}, ODEFunction{true, typeof(lorenz), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, OrdinaryDiffEq.VCABM5Cache{Vector{Float64}, Vector{Float64}, OrdinaryDiffEq.RK4Cache{Vector{Float64}, Vector{Float64}, Vector{Float64}}, Vector{Float64}, Matrix{Float64}, Vector{Float64}, Vector{Vector{Float64}}, Vector{Float64}}, OrdinaryDiffEq.DEOptions{Float64, Float64, Float64, Float64, PIController{Rational{Int64}}, typeof(DiffEqBase.ODE_DEFAULT_NORM), typeof(LinearAlgebra.opnorm), Nothing, CallbackSet{Tuple{}, Tuple{}}, typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN), typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE), typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK), DataStructures.BinaryMinHeap{Float64}, DataStructures.BinaryMinHeap{Float64}, Nothing, Nothing, Int64, Tuple{}, Tuple{}, Tuple{}}, Vector{Float64}, Float64, Nothing, OrdinaryDiffEq.DefaultInit})
    @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/WZTwh/src/solve.jl:475
  [4] #__solve#404
    @ ~/.julia/packages/OrdinaryDiffEq/WZTwh/src/solve.jl:5 [inlined]
  [5] __solve
    @ ~/.julia/packages/OrdinaryDiffEq/WZTwh/src/solve.jl:4 [inlined]
  [6] #solve_call#56
    @ ~/.julia/packages/DiffEqBase/U3Zj7/src/solve.jl:61 [inlined]
  [7] solve_call
    @ ~/.julia/packages/DiffEqBase/U3Zj7/src/solve.jl:48 [inlined]
  [8] #solve_up#58
    @ ~/.julia/packages/DiffEqBase/U3Zj7/src/solve.jl:82 [inlined]
  [9] solve_up
    @ ~/.julia/packages/DiffEqBase/U3Zj7/src/solve.jl:75 [inlined]
 [10] #solve#57
    @ ~/.julia/packages/DiffEqBase/U3Zj7/src/solve.jl:70 [inlined]
 [11] solve(prob::ODEProblem{Vector{Float64}, Tuple{Float64, Float64}, true, SciMLBase.NullParameters, ODEFunction{true, typeof(lorenz), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, args::VCABM5)
    @ DiffEqBase ~/.julia/packages/DiffEqBase/U3Zj7/src/solve.jl:68
 [12] top-level scope
    @ REPL[7]:1

julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cascadelake)
Environment:
  JULIA_NUM_THREADS = 12
```

The error message is rather bizarre, how can `end` be not defined? From the stack trace, it is only an `array[end]` operation. I found none of the VCABM algorithms work. I remember it has no such problem a few days ago.

I am on `[1dea7af3] OrdinaryDiffEq v5.54.0`. Thanks!

**Comment by devmotion** [comment] 2021-05-21 08:13
This seems to be a FastBroadcast issue caused by the `end` in https://github.com/SciML/OrdinaryDiffEq.jl/blob/3021916e201439166197f589b38d3a81949061ce/src/perform_step/adams_bashforth_moulton_perform_step.jl#L1319. An easy workaround would be to retrieve the last element before the broadcast operation, maybe this would also be more efficient if it is rewritten to a tight loop. However, in general I assume this should be supported by FastBroadcast?

@chriselrod @YingboMa

**Comment by chriselrod** [comment] 2021-05-21 08:58
> This seems to be a FastBroadcast issue caused by the `end` in
> 
> https://github.com/SciML/OrdinaryDiffEq.jl/blob/3021916e201439166197f589b38d3a81949061ce/src/perform_step/adams_bashforth_moulton_perform_step.jl#L1319
> . An easy workaround would be to retrieve the last element before the broadcast operation, maybe this would also be more efficient if it is rewritten to a tight loop. However, in general I assume this should be supported by FastBroadcast?
> 
> @chriselrod @YingboMa

Fixed by: https://github.com/YingboMa/FastBroadcast.jl/pull/17

**Comment by ChrisRackauckas** [comment] 2021-05-21 12:42
Thanks!

**Closed by ChrisRackauckas** 2021-05-21 12:42 UTC
