### ISSUE TITLE
Tracker downstream test is broken

### ISSUE THREAD

**Issue by YingboMa** [SciML/OrdinaryDiffEq.jl#1414] opened 2021-05-22 20:45 UTC
Introduced by #1384

We need to respect the return type of `internalnorm`. We want to AD through the controller when `t` is being differentiated.

CC: @ranocha, @ChrisRackauckas

**Comment by ChrisRackauckas** [comment] 2021-05-22 22:44
>We need to respect the return type of internalnorm. We want to AD through the controller when t is being differentiated.

Normally you don't want to differentiate through the controller even when differentiating through `t`.

**Comment by YingboMa** [comment] 2021-05-23 05:36
Ah, right. Controller should call `value` to strip the differentiation info.

**Comment by ranocha** [comment] 2021-05-23 06:17
So what's the conclusion? Is there some need to change something from #1348? Xref https://github.com/SciML/OrdinaryDiffEq.jl/pull/1384#discussion_r637448652

**Comment by ChrisRackauckas** [comment] 2021-05-23 14:00
Fixed by `ArrayInterface.ismutable(T::Type{<:Tracker.TrackedReal}) = false`. It looks like it was failing earlier with the newer RecursiveArrayTools, just using the wrong path because it thinks a TrackedReal is mutable.

**Comment by YingboMa** [comment] 2021-05-23 15:49
I don't think this completely fixes it. I had this locally when I was debugging yesterday. Something in the controller is throwing as well.

**Comment by YingboMa** [comment] 2021-05-23 15:50
Yep https://github.com/SciML/OrdinaryDiffEq.jl/pull/1416/checks?check_run_id=2650244244#step:6:782

**Comment by ChrisRackauckas** [comment] 2021-05-23 16:20
Fixed by https://github.com/SciML/OrdinaryDiffEq.jl/pull/1417, which is then matched in https://github.com/SciML/StochasticDiffEq.jl/pull/418 and https://github.com/SciML/StochasticDelayDiffEq.jl/pull/43. Interestingly, this must've been noticed in the DelayDiffEq.jl tests, so it already does the upconversion:

https://github.com/SciML/DelayDiffEq.jl/blob/master/src/solve.jl#L227

**Comment by ChrisRackauckas** [comment] 2021-05-23 16:20
Honestly, given that big of a change, I'm pretty happy this was the only regression we found. I expected more 😉. Let's see what the tests say.

**Closed** 2021-05-23 16:38 UTC
