### ISSUE TITLE
multithreaded solver gives wrong results

### ISSUE THREAD

**Issue by dabele** [SciML/OrdinaryDiffEq.jl#1989] opened 2023-07-19 11:53 UTC
I'm using the OrdinaryDiffEq package to solve a 2D PDE. When I activate activate multithreading for the ODE with julia --threads=8 and `thread=True()`, the result is tiled like this:

![thread_tiles](https://github.com/SciML/OrdinaryDiffEq.jl/assets/4610154/46f8c5c4-5aa8-4655-8a0b-709ae5cf2668)

this is basically just the lower left corner of my problem repeated. The number of tiles matches the number of threads.

I think I can reproduce the issue with a much simpler problem, even just two independent scalar exponentials with different initial values:

```
import OrdinaryDiffEq as Ode

# two independent exponentials
function f!(du, u, p, t)
    du[:] = u[:]
end

u0 = [1.0, 2.0]
tspan = (0.0, 1.0)
prob = Ode.ODEProblem(f!, u0, tspan)
sol = Ode.solve(prob, Ode.Midpoint(thread=Ode.True()), dt = 0.1)

using Plots: plot, plot!
plot(sol, xaxis="t",yaxis="u(t)",label="u")
```

expected result: 
![exp2](https://github.com/SciML/OrdinaryDiffEq.jl/assets/4610154/c57970fd-b84c-4419-9a70-579d6208cc94)

result when multi threading is enabled:
![exp2_mt](https://github.com/SciML/OrdinaryDiffEq.jl/assets/4610154/f2fc9f01-96d2-4906-a7c6-839528209631)

The second exponential snaps to the first at the first time step, which is basically the same as with the tiled 2D PDE as well. With `thread=Ode.False()` everything works as expected.

I tried different solvers other than midpoint as well. I also tried the Lorentz equations from your examples:
```
function f!(du, u, p, t)
    du[1] = 10.0 * (u[2] - u[1])
    du[2] = u[1] * (28.0 - u[3]) - u[2]
    du[3] = u[1] * u[2] - (8 / 3) * u[3]
end
u0 = [1.0; 0.0; 0.0]
```

since these are such simple examples, I must be missing something obvious, but haven't found a solution in your docs or the julia docs.

**Comment by ranocha** [comment] 2023-07-19 12:10
I can't reproduce this locally:

```julia
(@v1.9) pkg> activate --temp
  Activating new project at `/tmp/jl_z4XLcN`

(jl_z4XLcN) pkg> add OrdinaryDiffEq
   Resolving package versions...
    Updating `/tmp/jl_z4XLcN/Project.toml`
  [1dea7af3] + OrdinaryDiffEq v6.53.3

julia> import OrdinaryDiffEq as Ode

julia> # two independent exponentials
       function f!(du, u, p, t)
           du[:] = u[:]
       end
f! (generic function with 1 method)

julia> u0 = [1.0, 2.0]
2-element Vector{Float64}:
 1.0
 2.0

julia> tspan = (0.0, 1.0)
(0.0, 1.0)

julia> prob = Ode.ODEProblem(f!, u0, tspan)
ODEProblem with uType Vector{Float64} and tType Float64. In-place: true
timespan: (0.0, 1.0)
u0: 2-element Vector{Float64}:
 1.0
 2.0

julia> sol = Ode.solve(prob, Ode.Midpoint(thread=Ode.True()), dt = 0.1)
retcode: Success
Interpolation: 3rd order Hermite
t: 35-element Vector{Float64}:
 0.0
 0.04317697934316054
 0.05181237521179265
 0.0759111239150825
 0.0933478153832657
 0.1170746501349594
 0.14001951650007732
 0.16567413172654177
 0.1918788056413178
 0.2194449233202017
 0.24768067214716508
 0.2767022525096068
 0.30625065030597015
 0.3362874759727627
 0.36669222837700277
 0.3974098438644505
 0.428373370068236
 0.45953905357111596
 0.490865989890669
 0.522323668282656
 0.5538861153505045
 0.5855330024939086
 0.6172476255188387
 0.6490166835967872
 0.6808294011404479
 0.7126771490050996
 0.7445529768256055
 0.7764513040712906
 0.8083676559933106
 0.840298435189663
 0.8722407571622828
 0.9041923081521661
 0.9361512340698793
 0.9681160438264738
 1.0
u: 35-element Vector{Vector{Float64}}:
 [1.0, 2.0]
 [1.0441091051157605, 2.088218210231521]
 [1.0531643302087297, 2.1063286604174594]
 [1.0788500851743497, 2.1577001703486993]
 [1.0978256670739883, 2.1956513341479766]
 [1.124182612706701, 2.248365225413402]
 [1.1502727549886098, 2.3005455099772196]
 [1.1801610912688318, 2.3603221825376637]
 [1.2114920272535497, 2.4229840545070993]
 [1.2453484598933262, 2.4906969197866524]
 [1.2810082379161611, 2.5620164758323223]
 [1.318724587394169, 2.637449174788338]
 [1.3582664804561213, 2.7165329609122426]
 [1.3996772153478925, 2.799354430695785]
 [1.4428810196055661, 2.8857620392111323]
 [1.4878836149534087, 2.9757672299068174]
 [1.534666984988204, 3.069333969976408]
 [1.5832412414140982, 3.1664824828281963]
 [1.6336162171841004, 3.267232434368201]
 [1.6858142922451094, 3.3716285844902187]
 [1.7398624106491134, 3.479724821298227]
 [1.795794898259662, 3.591589796519324]
 [1.8536509772882441, 3.7073019545764883]
 [1.9134751428307772, 3.8269502856615545]
 [1.9753162523765022, 3.9506325047530044]
 [2.0392273872752167, 4.078454774550433]
 [2.105265445612402, 4.210530891224804]
 [2.1734909489847993, 4.346981897969599]
 [2.2439678681148703, 4.4879357362297405]
 [2.3167634570235447, 4.633526914047089]
 [2.3919481720027633, 4.783896344005527]
 [2.4695955978563733, 4.939191195712747]
 [2.5497824096803514, 5.099564819360703]
 [2.6325883382201805, 5.265176676440361]
 [2.717863796513561, 5.435727593027122]

julia> Threads.nthreads()
4
```

The two components are not the same here. Which versions of Julia and the packages are you using? Do you get the same wrong results on other systems and with different numbers of threads?

**Comment by dabele** [comment] 2023-07-19 16:12
Tried to narrow it down some more. it seems that Trixi (the PDE framework) has some kind of conflict with OrdinaryDiffEq.

This is what I ran (file `ode.jl` contains the code I posted above)
```
$ julia --threads=2
julia> include("ode.jl")
julia> using Trixi
julia> include("ode.jl")
```
The first run gives the expected result. The second run is wrong. I tried this in a completely new environment on a system where I just installed Julia, I only added Trixi, OrdinaryDiffEq and Plots to the environment. The new system is Windows 10, the first one was Ubuntu.

Versions:
Julia 1.9.2
OrdinaryDiffEq 6.53.3
Trixi 0.5.35

I'm new to julia, so I don't really know where the conflict could be coming from. But it's probably good to close this and reopen an issue for Trixi.

**Comment by ranocha** [comment] 2023-07-20 07:37
Reduced:
```julia
(@v1.9) pkg> activate --temp

(jl_gRLcyz) pkg> add OrdinaryDiffEq StrideArrays

julia> using OrdinaryDiffEq

julia> ode = ODEProblem((du, u, p, t) -> du .= u, [1.0, 2.0], (0.0, 1.0))

julia> solve(ode, Midpoint(thread = OrdinaryDiffEq.True()), dt = 0.1)
...
 [2.3919481720027633, 4.783896344005527]
 [2.4695955978563733, 4.939191195712747]
 [2.5497824096803514, 5.099564819360703]
 [2.6325883382201805, 5.265176676440361]
 [2.717863796513561, 5.435727593027122]

julia> using StrideArrays

julia> solve(ode, Midpoint(thread = OrdinaryDiffEq.True()), dt = 0.1)
...
 [2.3921319375213854, 2.3921319375213854]
 [2.4697898814002475, 2.4697898814002475]
 [2.549987551988969, 2.549987551988969]
 [2.63280469689671, 2.63280469689671]
 [2.7178638061237126, 2.7178638061237126]
```

**Comment by ranocha** [comment] 2023-07-20 07:47
@chriselrod Do you have any idea what's going on here? With `thread = OrdinaryDiffEq.True()`, it uses something like
https://github.com/SciML/OrdinaryDiffEq.jl/blob/780c94aa8944979d9dcbfb0e34c1f2554727a471/src/perform_step/fixed_timestep_perform_step.jl#L250
with `@..` from FastBroadcast.jl

**Comment by ChrisRackauckas** [comment] 2023-07-20 07:48
Check Polyester threads?

**Comment by ranocha** [comment] 2023-07-20 09:08
What exactly do you mean?

**Comment by ChrisRackauckas** [comment] 2023-07-20 09:28
`thread = OrdinaryDiffEq.PolyesterThreads()`

**Comment by chriselrod** [comment] 2023-07-20 10:39
> @chriselrod Do you have any idea what's going on here? With `thread = OrdinaryDiffEq.True()`, it uses something like
> 
> https://github.com/SciML/OrdinaryDiffEq.jl/blob/780c94aa8944979d9dcbfb0e34c1f2554727a471/src/perform_step/fixed_timestep_perform_step.jl#L250
> 
> with `@..` from FastBroadcast.jl. Somehow, `using StrideArrays` breaks this...

`using StrideArrays` shouldn't change Fastbroadcast.jl, but did change base broadcast.

**Comment by ranocha** [comment] 2023-07-20 11:56
> `thread = OrdinaryDiffEq.PolyesterThreads()`

That's used in another context. here, we just allow `Static.True` and `Static.False`

**Comment by ranocha** [comment] 2023-07-20 14:30
> `using StrideArrays` shouldn't change Fastbroadcast.jl

It does - at least on my system. I started Julia v1.9.2 with 2 threads and get

```julia
julia> using Pkg; Pkg.activate(temp = true); Pkg.add(["FastBroadcast", "StrideArrays"])

julia> using FastBroadcast

julia> u = [1.0, 2.0]
2-element Vector{Float64}:
 1.0
 2.0

julia> v = [1.0, 2.0]
2-element Vector{Float64}:
 1.0
 2.0

julia> w = zero(u)
2-element Vector{Float64}:
 0.0
 0.0

julia> @.. broadcast=false thread=true w = u + 1.0 * v
2-element Vector{Float64}:
 2.0
 4.0

julia> using StrideArrays

julia> @.. broadcast=false thread=true w = u + 1.0 * v
2-element Vector{Float64}:
 2.0
 2.0
```

Any idea what's going on here, @chriselrod?

**Comment by chriselrod** [comment] 2023-07-20 15:18
So @ranocha, the problem is likely that we take views of the broadcasted objects via
https://github.com/YingboMa/FastBroadcast.jl/blob/3f8fb067a9efe1d441f8f7bec08f6992cef6c324/src/FastBroadcast.jl#L58-L69
But `StrideArray`s adds a different broadcast style for `StrideArray`s (so that they can use LV), which then probably hits the fallback definition.
https://github.com/YingboMa/FastBroadcast.jl/blob/3f8fb067a9efe1d441f8f7bec08f6992cef6c324/src/FastBroadcast.jl#L54

**Comment by chriselrod** [comment] 2023-07-20 21:52
Can you confirm it has now been fixed?

**Comment by chriselrod** [comment] 2023-07-20 21:52
The secondary/possible performance issue I reported above of "too many threads" is fixed by https://github.com/JuliaSIMD/Polyester.jl/pull/114

**Comment by ranocha** [comment] 2023-07-21 05:18
I can confirm that it's working for me after updating Polyester.jl and FastBroadcast.jl. Thanks for the quick fix, @chriselrod :+1: 

I'll close this issue. Please let us know if there are still problems for you, @dabele.

**Closed by ranocha** 2023-07-21 05:18 UTC
