### ISSUE TITLE
Default solve call crashes with complex state variable

### ISSUE THREAD

**Issue by zmorrell** [SciML/OrdinaryDiffEq.jl#2380] opened 2024-08-13 16:29 UTC
**Describe the bug 🐞**

When I use the default stiff solver for the a complex valued differential equation, `solve` crashes with an error regarding `isless` being unable to compare Complex64 numbers.  This issue only seems to occur with Julia 1.10 (I have specifically tested on 1.10.4 and 1.10.3), but does not seem to be an issue on Julia <= 1.9.4

**Expected behavior**

I expect the function to be able to solve the Schrodinger Equation (example shown below).  This has historically worked well and works well if I specify the algorithm to be for example `Tsit5`. Note that in the instance that I show below I am using the time normalized Schrodinger Equation, so time is a parameter and the "s" value is the varying component.

**Minimal Reproducible Example 👇**

```julia
import OrdinaryDiffEq

sig_X = complex([0 1; 1 0])
sig_Z = complex([1 0; 0 -1])

initial_state = complex(1/sqrt(2) * [1; -1])

H(s) = (1-s) * sig_X + (s) * sig_Z
schrod_eq(state, time, s) = -im * time * H(s) * state

s_range = (0,1)

evolution_time = 100

prob = OrdinaryDiffEq.ODEProblem(schrod_eq, initial_state, s_range, evolution_time)
sol = OrdinaryDiffEq.solve(prob)

```

**Error & Stacktrace ⚠️**

```julia
ERROR: LoadError: MethodError: no method matching isless(::ComplexF64, ::ComplexF64)

Closest candidates are:
  isless(::Missing, ::Any)
   @ Base missing.jl:87
  isless(::Any, ::Missing)
   @ Base missing.jl:88

Stacktrace:
  [1] max(x::ComplexF64, y::ComplexF64)
    @ Base ./operators.jl:476
  [2] _mapreduce
    @ ./reduce.jl:440 [inlined]
  [3] _mapreduce_dim
    @ ./reducedim.jl:365 [inlined]
  [4] mapreduce
    @ ./reducedim.jl:357 [inlined]
  [5] _maximum
    @ ./reducedim.jl:1015 [inlined]
  [6] _maximum
    @ ./reducedim.jl:1014 [inlined]
  [7] maximum(a::Vector{ComplexF64})
    @ Base ./reducedim.jl:1010
  [8] perform_step!(integrator::OrdinaryDiffEq.ODEIntegrator{…}, cache::OrdinaryDiffEq.Tsit5ConstantCache, repeat_step::Bool)
    @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/s27pa/src/perform_step/low_order_rk_perform_step.jl:765
  [9] perform_step!(integrator::OrdinaryDiffEq.ODEIntegrator{…}, cache::OrdinaryDiffEq.DefaultCache{…}, repeat_step::Bool)
    @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/s27pa/src/perform_step/composite_perform_step.jl:105
 [10] perform_step!
    @ ~/.julia/packages/OrdinaryDiffEq/s27pa/src/perform_step/composite_perform_step.jl:102 [inlined]
 [11] solve!(integrator::OrdinaryDiffEq.ODEIntegrator{…})
    @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/s27pa/src/solve.jl:557
 [12] #__solve#433
    @ ~/.julia/packages/OrdinaryDiffEq/s27pa/src/solve.jl:7 [inlined]
 [13] __solve
    @ ~/.julia/packages/OrdinaryDiffEq/s27pa/src/solve.jl:1 [inlined]
 [14] solve_call(_prob::SciMLBase.ODEProblem{…}, args::OrdinaryDiffEq.CompositeAlgorithm{…}; merge_callbacks::Bool, kwargshandle::Nothing, kwargs::@Kwargs{…})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:612
 [15] solve_call
    @ ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:569 [inlined]
 [16] solve_up(prob::SciMLBase.ODEProblem{…}, sensealg::Nothing, u0::Vector{…}, p::Int64, args::OrdinaryDiffEq.CompositeAlgorithm{…}; kwargs::@Kwargs{…})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:1080
 [17] solve_up
    @ ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:1066 [inlined]
 [18] #solve#51
    @ ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:1003 [inlined]
 [19] solve
    @ ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:993 [inlined]
 [20] #__solve#438
    @ ~/.julia/packages/OrdinaryDiffEq/s27pa/src/solve.jl:547 [inlined]
 [21] __solve
    @ ~/.julia/packages/OrdinaryDiffEq/s27pa/src/solve.jl:546 [inlined]
 [22] #__solve#72
    @ ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:1394 [inlined]
 [23] __solve
    @ ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:1386 [inlined]
 [24] #solve_call#44
    @ ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:612 [inlined]
 [25] solve_call(::SciMLBase.ODEProblem{Vector{…}, Tuple{…}, false, Int64, SciMLBase.ODEFunction{…}, @Kwargs{}, SciMLBase.StandardODEProblem})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:569
 [26] solve_up(::SciMLBase.ODEProblem{Vector{…}, Tuple{…}, false, Int64, SciMLBase.ODEFunction{…}, @Kwargs{}, SciMLBase.StandardODEProblem}, ::Nothing, ::Vector{ComplexF64}, ::Int64; kwargs::@Kwargs{})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:1072
 [27] solve_up
    @ ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:1066 [inlined]
 [28] solve(::SciMLBase.ODEProblem{Vector{…}, Tuple{…}, false, Int64, SciMLBase.ODEFunction{…}, @Kwargs{}, SciMLBase.StandardODEProblem}; sensealg::Nothing, u0::Nothing, p::Nothing, wrap::Val{true}, kwargs::@Kwargs{})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:1003
 [29] solve(::SciMLBase.ODEProblem{Vector{…}, Tuple{…}, false, Int64, SciMLBase.ODEFunction{…}, @Kwargs{}, SciMLBase.StandardODEProblem})
    @ DiffEqBase ~/.julia/packages/DiffEqBase/V6SCE/src/solve.jl:993
 [30] top-level scope
    @ ~/Development/temp/broken_example.jl:16
 [31] include(fname::String)
    @ Base.MainInclude ./client.jl:489
 [32] top-level scope
    @ REPL[2]:1
in expression starting at /home/zmorrell/Development/temp/broken_example.jl:16
Some type information was truncated. Use `show(err)` to see complete types.

```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `~/Development/temp/dev/Project.toml`
  [1dea7af3] OrdinaryDiffEq v6.87.0
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia

Status `~/Development/temp/dev/Manifest.toml`
  [47edcb42] ADTypes v1.7.1
  [7d9f7c33] Accessors v0.1.37
  [79e6a3ab] Adapt v4.0.4
  [ec485272] ArnoldiMethod v0.4.0
  [4fba245c] ArrayInterface v7.15.0
  [4c555306] ArrayLayouts v1.10.2
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [2a0fbf3d] CPUSummary v0.2.6
  [d360d2e6] ChainRulesCore v1.24.0
  [fb6a15b2] CloseOpenIntervals v0.1.13
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.0
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.16.0
  [a33af91c] CompositionsBase v0.1.2
  [2569d6c7] ConcreteStructs v0.2.3
  [187b0558] ConstructionBase v1.5.6
  [adafc99b] CpuId v0.3.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.18.20
  [e2d170a0] DataValueInterfaces v1.0.0
  [2b5f629d] DiffEqBase v6.152.2
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.5.12
  [ffbed154] DocStringExtensions v0.9.3
  [4e289a0a] EnumX v1.0.4
  [f151be2c] EnzymeCore v0.7.8
  [d4d017d3] ExponentialUtilities v1.26.1
  [e2ba6199] ExprTools v0.1.10
⌅ [6b7a57c9] Expronicon v0.8.5
  [7034ab61] FastBroadcast v0.3.5
  [9aa1b823] FastClosures v0.3.2
  [29a986be] FastLapackInterface v2.0.4
  [1a297f60] FillArrays v1.11.0
  [6a86dc24] FiniteDiff v2.24.0
  [f6369f11] ForwardDiff v0.10.36
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [46192b85] GPUArraysCore v0.1.6
  [c145ed77] GenericSchur v0.5.4
  [86223c79] Graphs v1.11.2
  [3e5b6fbb] HostCPUFeatures v0.1.17
  [615f187c] IfElse v0.1.1
  [d25df0c9] Inflate v0.1.5
  [3587e190] InverseFunctions v0.1.16
  [92d709cd] IrrationalConstants v0.2.2
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.5.0
  [ef3ab10e] KLU v0.6.0
  [ba0b0d4f] Krylov v0.9.6
  [10f19ff3] LayoutPointers v0.1.17
  [5078a376] LazyArrays v2.2.0
  [d3d80556] LineSearches v7.3.0
  [7ed4a6bd] LinearSolve v2.32.0
  [2ab3a3ac] LogExpFunctions v0.3.28
  [bdcacae8] LoopVectorization v0.12.171
  [d8e11817] MLStyle v0.4.17
  [1914dd2f] MacroTools v0.5.13
  [d125e4d3] ManualMemory v0.1.8
  [bb5d69b7] MaybeInplace v0.1.3
  [46d2c3a1] MuladdMacro v0.2.4
  [d41bc354] NLSolversBase v7.8.3
  [77ba4419] NaNMath v1.0.2
  [8913a72c] NonlinearSolve v3.14.0
  [6fe1bfb0] OffsetArrays v1.14.1
  [bac558e1] OrderedCollections v1.6.3
  [1dea7af3] OrdinaryDiffEq v6.87.0
  [65ce6f38] PackageExtensionCompat v1.0.2
  [d96e819e] Parameters v0.12.3
  [f517fe37] Polyester v0.7.16
  [1d0040c9] PolyesterWeave v0.2.2
  [d236fae5] PreallocationTools v0.4.23
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.27.0
  [f2c3362d] RecursiveFactorization v0.2.23
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.0
  [7e49a35a] RuntimeGeneratedFunctions v0.5.13
  [94e857df] SIMDTypes v0.1.0
  [476501e8] SLEEFPirates v0.6.43
  [0bca4576] SciMLBase v2.48.1
  [c0aeaf25] SciMLOperators v0.3.9
  [53ae85a6] SciMLStructures v1.4.2
  [efcf1570] Setfield v1.1.1
  [727e6d20] SimpleNonlinearSolve v1.12.0
  [699a6c99] SimpleTraits v0.9.4
  [ce78b400] SimpleUnPack v1.1.0
  [47a9eef4] SparseDiffTools v2.20.0
  [0a514795] SparseMatrixColorings v0.3.6
  [e56a9233] Sparspak v0.3.9
  [276daf66] SpecialFunctions v2.4.0
  [aedffcd0] Static v1.1.1
  [0d7ed370] StaticArrayInterface v1.8.0
  [90137ffa] StaticArrays v1.9.7
  [1e83bf80] StaticArraysCore v1.4.3
  [7792a7ef] StrideArraysCore v0.5.7
  [2efcf032] SymbolicIndexingInterface v0.3.28
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.0
  [8290d209] ThreadingUtilities v0.5.2
  [a759f4b9] TimerOutputs v0.5.24
  [d5829a12] TriangularSolve v0.2.1
  [410a4b4d] Tricks v0.1.9
  [781d530d] TruncatedStacktraces v1.4.0
  [3a884ed6] UnPack v1.0.2
  [3d5dd08c] VectorizationBase v0.21.70
  [19fa3120] VertexSafeGraphs v0.2.0
  [1d5cc7b8] IntelOpenMP_jll v2024.2.0+0
  [856f044c] MKL_jll v2024.2.0+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [1317d2d5] oneTBB_jll v2021.12.0+0
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.10.0
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays v1.10.0
  [10745b16] Statistics v1.10.0
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] LibCURL_jll v8.4.0+0
  [e37daf67] LibGit2_jll v1.6.4+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.2+1
  [14a3606d] MozillaCACerts_jll v2023.1.10
  [4536629a] OpenBLAS_jll v0.3.23+4
  [05823500] OpenLibm_jll v0.8.1+2
  [bea87d4a] SuiteSparse_jll v7.2.1+1
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.8.0+1
  [8e850ede] nghttp2_jll v1.52.0+1
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
```

  - Output of `versioninfo()`

```julia

Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  LD_ARGV0_REL = ../bin/vshd
```

**Additional context**

The above code will work without issue if you specify the algorithm (i.e. changing the line `sol = OrdinaryDiffEq.solve(prob)` to `sol = OrdinaryDiffEq.solve(prob, OrdinaryDiffEq.Tsit5())`.  This leads me to believe it is an issue with the default algorithm for nonstiff problems.  I have also tested using `alg_hints = [:nonstiff]`.  Also, as mentioned above, I have tested with both Julia 1.10.4 and 1.10.3 and it works with Julia 1.9.4.

**Comment by oscardssmith** [comment] 2024-08-13 16:49
good catch. Will fix and add a test. The issue is that with the automatic algorithm we compute a stiffness estimate that isn't getting computed correctly for complex numbers.

**Comment by oscardssmith** [comment] 2024-08-13 17:02
This will be fixed by https://github.com/SciML/OrdinaryDiffEq.jl/pull/2381 but it might take a little bit to get released since we're about 80% done with a giant refactor at the moment.

**Closed** 2024-08-13 21:10 UTC
Labels: bug
