### ISSUE TITLE
fixed dt step! may fail due to t being close to tstop

### ISSUE THREAD

**Issue by daviehh** [SciML/OrdinaryDiffEq.jl#1879] opened 2023-02-20 02:10 UTC
When directly using the Integrator Interface to advance, the integrator's time may become very close to existing tstop due to floating point arithmetic and fails to advance:

```julia
using OrdinaryDiffEq

function ode_fx(du, u, p, t)
    du[1] = p
end

tf = 10
prob = ODEProblem(ode_fx, [0], (0, tf), 1.0)

itg = init(prob, Vern9(), tstops=[0.1])

for i in 1:20
    step!(itg, 0.01, true)
    if !(SciMLBase.successful_retcode(check_error(itg)))
        break
    end
end

```

fails to adavnce past `t`~0.1 due to
```
┌ Warning: dt(1.3877787807814457e-17) <= dtmin(1.7763568394002505e-15) at t=0.09999999999999999. Aborting.
│ There is either an error in your model specification or the true solution is unstable.
└ @ SciMLBase /Users/david/.julia/packages/SciMLBase/K7a7T/src/integrator_interface.jl:529
```
where
`println(0.1 - itg.t)`
> 1.3877787807814457e-17

setting `advance_to_tstop` does not seem to help, `itg = init(prob, Vern9(), tstops=[0.1], advance_to_tstop=true)` still fails to advance. Should this be handled in the package or it's a case of "using it wrong"? Thanks!

**Comment by oscardssmith** [comment] 2023-02-20 02:18
I think this is a duplicate of https://github.com/SciML/OrdinaryDiffEq.jl/issues/1616

**Comment by ChrisRackauckas** [comment] 2023-02-20 02:24
It should get fixed, but it's one of those things that's surprisingly difficult and making sure to give good inputs would definitely help it. But it is on my mind to solve someday.

**Closed** 2023-12-30 12:11 UTC
