### ISSUE TITLE
Precompilation error: num_threads not defined

### ISSUE THREAD

**Issue by DanielVandH** [SciML/OrdinaryDiffEq.jl#1827] opened 2023-01-04 03:55 UTC
Doing `using OrdinaryDiffEq` seems to lead to precompilation errors with `num_threads` no longer being a function:

```
julia> using OrdinaryDiffEq
[ Info: Precompiling OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]
ERROR: LoadError: UndefVarError: num_threads not defined
Stacktrace:
 [1] include
   @ .\Base.jl:422 [inlined]
 [2] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base .\loading.jl:1407
 [3] top-level scope
   @ stdin:1
in expression starting at C:\Users\licer\.julia\packages\Polyester\JGkMZ\src\Polyester.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile Polyester [f517fe37-dbe3-4b94-8317-1923a5111588] to C:\Users\licer\.julia\compiled\v1.8\Polyester\jl_4035.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
    @ Base .\loading.jl:1558
  [3] compilecache
    @ .\loading.jl:1502 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1203
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1091
  [6] macro expansion
    @ .\loading.jl:1071 [inlined]
  [7] macro expansion
    @ .\lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1035
  [9] include
    @ .\Base.jl:422 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base .\loading.jl:1407
 [11] top-level scope
    @ stdin:1
in expression starting at C:\Users\licer\.julia\packages\FastBroadcast\1cc7o\src\FastBroadcast.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile FastBroadcast [7034ab61-46d4-4ed7-9d0f-46aef9175898] to C:\Users\licer\.julia\compiled\v1.8\FastBroadcast\jl_3DE4.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
    @ Base .\loading.jl:1558
  [3] compilecache
    @ .\loading.jl:1502 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1203
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1091
  [6] macro expansion
    @ .\loading.jl:1071 [inlined]
  [7] macro expansion
    @ .\lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1035
  [9] include
    @ .\Base.jl:422 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base .\loading.jl:1407
 [11] top-level scope
    @ stdin:1
in expression starting at C:\Users\licer\.julia\packages\DiffEqBase\9H9Sj\src\DiffEqBase.jl:1
in expression starting at stdin:1
ERROR: LoadError: Failed to precompile DiffEqBase [2b5f629d-d688-5b77-993f-72d75c75574e] to C:\Users\licer\.julia\compiled\v1.8\DiffEqBase\jl_3681.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
    @ Base .\loading.jl:1558
  [3] compilecache
    @ .\loading.jl:1502 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1203
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1091
  [6] macro expansion
    @ .\loading.jl:1071 [inlined]
  [7] macro expansion
    @ .\lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1035
  [9] include
    @ .\Base.jl:422 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base .\loading.jl:1407
 [11] top-level scope
    @ stdin:1
in expression starting at C:\Users\licer\.julia\packages\OrdinaryDiffEq\CFzwI\src\OrdinaryDiffEq.jl:1
in expression starting at stdin:1
ERROR: Failed to precompile OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed] to C:\Users\licer\.julia\compiled\v1.8\OrdinaryDiffEq\jl_3327.tmp.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
    @ Base .\loading.jl:1558
  [3] compilecache
    @ .\loading.jl:1502 [inlined]
  [4] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:1203
  [5] _require_prelocked(uuidkey::Base.PkgId)
    @ Base .\loading.jl:1091
  [6] macro expansion
    @ .\loading.jl:1071 [inlined]
  [7] macro expansion
    @ .\lock.jl:223 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:1035
  [9] eval
    @ .\boot.jl:368 [inlined]
 [10] eval
    @ .\Base.jl:65 [inlined]
 [11] repleval(m::Module, code::Expr, #unused#::String)
    @ VSCodeServer c:\Users\licer\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\repl.jl:222
 [12] (::VSCodeServer.var"#107#109"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
    @ VSCodeServer c:\Users\licer\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\repl.jl:186
 [13] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging .\logging.jl:511
 [14] with_logger
    @ .\logging.jl:623 [inlined]
 [15] (::VSCodeServer.var"#106#108"{Module, Expr, REPL.LineEditREPL, REPL.LineEdit.Prompt})()
    @ VSCodeServer c:\Users\licer\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\repl.jl:187
 [16] #invokelatest#2
    @ .\essentials.jl:729 [inlined]
 [17] invokelatest(::Any)
    @ Base .\essentials.jl:726
 [18] macro expansion
    @ c:\Users\licer\.vscode\extensions\julialang.language-julia-1.38.2\scripts\packages\VSCodeServer\src\eval.jl:34 [inlined]
 [19] (::VSCodeServer.var"#61#62")()
    @ VSCodeServer .\task.jl:482
```

Status/version info:

```
(jl_UuPYm0) pkg> st
Status `C:\Users\licer\AppData\Local\Temp\jl_UuPYm0\Project.toml`
  [1dea7af3] OrdinaryDiffEq v6.36.2

julia> versioninfo()
Julia Version 1.8.0-rc1
Commit 6368fdc656 (2022-05-27 18:33 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 8 on 12 virtual cores
Environment:
  JULIA_PKG_USE_CLI_GIT = true
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```

**Comment by ChrisRackauckas** [comment] 2023-01-04 05:56
Duplicate of https://github.com/SciML/OrdinaryDiffEq.jl/issues/1828 . @chriselrod @YingboMa let's fix this fast please.

**Closed by ChrisRackauckas** 2023-01-04 05:56 UTC

**Comment by chriselrod** [comment] 2023-01-04 06:01
I should have bumped the version of PolyesterWeave.
It was not exporting `num_threads`, but if packages were importing it from there...

**Comment by chriselrod** [comment] 2023-01-04 06:03
This is a hot fix:
https://github.com/JuliaRegistries/General/pull/75041
But we'll role out packages dependent on PolyesterWeave 0.2.
