### ISSUE TITLE
Type of array changes when using non-standard array types

### ISSUE THREAD

**Issue by jlchan** [SciML/OrdinaryDiffEq.jl#1386] opened 2021-04-23 04:02 UTC
I'm trying to use StructArrays with OrdinaryDiffEq.jl. StructArrays seem compatible with some of the nested array functionality introduced in e.g., https://github.com/SciML/DiffEqBase.jl/issues/619, but it seems like the type of the array gets changed in `solve`. For example, 

```julia
using OrdinaryDiffEq
using StaticArrays
using StructArrays

function rhs!(du::StructArray,u,p,t)
    du .= u
    return nothing
end
struct Foo{T} <: FieldVector{2,T}
    u::T
    v::T
end
u = StructArray([Foo(1.,2.) for i = 1:5])
du = similar(u)
prob = ODEProblem(rhs!,u,(0.0,.1))
sol = solve(prob,Tsit5())
```
returns `ERROR: MethodError: no method matching rhs!(::Vector{Foo{Float64}}, ::Vector{Foo{Float64}}, ::SciMLBase.NullParameters, ::Float64)`, e.g., `du` gets changed from a StructArray of Foo to a Vector of Foo. 

I can get around this by converting to StructArray on the fly for now, but I'd be interested in making OrdinaryDiffEq.jl work with StructArrays. Is it known where `du` gets modified, and is it possible to fix this by extending some functions to StructArrays?

**Comment by ranocha** [comment] 2021-04-23 05:21
The problem is
```julia
julia> using StructArrays, StaticArrays, RecursiveArrayTools

julia> struct Foo{T} <: FieldVector{2,T}
           u::T
           v::T
       end

julia> u = StructArray([Foo(1.,2.) for i = 1:5]); typeof(u)
StructVector{Foo{Float64}, NamedTuple{(:u, :v), Tuple{Vector{Float64}, Vector{Float64}}}, Int64} (alias for StructArray{Foo{Float64}, 1, NamedTuple{(:u, :v), Tuple{Array{Float64, 1}, Array{Float64, 1}}}, Int64})

julia> recursivecopy(u)
5-element Vector{Foo{Float64}}:
 [1.0, 2.0]
 [1.0, 2.0]
 [1.0, 2.0]
 [1.0, 2.0]
 [1.0, 2.0]
```
Here, `recursivecopy(u)` calls `map(recursivecopy, u)`, which in turn results in a `Vector` as outer storage type. Thus, I guess StructArrays needs to know about RecursiveArrayTools and implement a specialization of `recursivecopy` to make this work as intended.

**Comment by jlchan** [comment] 2021-04-23 05:23
That fixes it - just added `RecursiveArrayTools.recursivecopy(u::StructArray) = copy(u)` and it works. Thanks @ranocha!

**Comment by ranocha** [comment] 2021-04-23 05:25
I think you shouldn't close this here - it should be fixed in StructArrays and/or RecursiveArrayTools.

**Comment by jlchan** [comment] 2021-04-23 05:25
I'm not sure if StructArrays would want to take on RecursiveArrayTools as a dependency, but

**Comment by ChrisRackauckas** [comment] 2021-04-23 05:28
>Here, recursivecopy(u) calls map(recursivecopy, u), which in turn results in a Vector as outer storage type.

The fallback on AbstractArray is to call `copy` IIRC?

**Comment by ranocha** [comment] 2021-04-23 05:30
In this example, `Foo{T} <: FieldVector{2,T} <: AbstractArray`, so it hits https://github.com/SciML/RecursiveArrayTools.jl/blob/c5f8fa7cfc9fa94bb8f8d8111391222288948192/src/utils.jl#L9-L11

**Comment by ChrisRackauckas** [comment] 2021-04-23 05:32
`Foo{T} <: FieldVector{2,T} <: AbstractArray{T}` where `T <: Number` would hit:

https://github.com/SciML/RecursiveArrayTools.jl/blob/c5f8fa7cfc9fa94bb8f8d8111391222288948192/src/utils.jl#L5-L7

?

**Comment by ChrisRackauckas** [comment] 2021-04-23 05:33
Oh wait, I didn't know this was an array of arrays structure, I see.

**Comment by ChrisRackauckas** [comment] 2021-04-23 05:37
We could do `if ArrayInterface.mutable(a)`, then use `b = similar(a); map!(b,recursivecopy,a)` ?

Indeed, the underlying issue here is that the idea of a "type-preserving map" doesn't exist. The non-mutable branch should make use of https://github.com/JuliaArrays/ArrayInterface.jl#restructurexy, i.e.:

```julia
function recursivecopy(a::AbstractArray{T,N}) where {T<:AbstractArray,N}
  if ArrayInterface.mutable(a)
    b = similar(a)
    map!(b,recursivecopy,a)
  else
    ArrayInterface.restructure(a,map(recursivecopy,a))
  end
end
```

And from that you can see exactly what trait is missing in Base here, so we just need an `@requires` in ArrayInterface.jl which sets a few traits.

**Comment by ranocha** [comment] 2021-04-23 05:41
That sounds reaonable. StructArrays would only need to depend on ArrayInterface and the rest should work with this change, I guess

**Comment by jlchan** [comment] 2021-04-23 06:03
Works great for me. With
```julia
function RecursiveArrayTools.recursivecopy(a::AbstractArray{T,N}) where {T<:AbstractArray,N}
    if ArrayInterface.ismutable(a)
      b = similar(a)
      map!(recursivecopy,b,a)
    else
      ArrayInterface.restructure(a,map(recursivecopy,a))
    end
end
ArrayInterface.ismutable(x::StructArray) = true
```
then `recursivecopy(u)` returns a regular StructArray.

**Comment by jlchan** [comment] 2021-04-23 06:06
@piever would supporting ArrayInterface in StructArrays be something you'd be open to?

**Comment by piever** [comment] 2021-04-23 14:53
I confess that I would prefer to not add any more dependencies to StructArrays. Can't this method be added in ArrayInterface in a Require block? It seems like that was the approach taken with other array types (OffsetArrays, StaticArrays, etc.).

**Comment by jlchan** [comment] 2021-04-23 17:13
@piever oops, nevermind - I spoke too soon. It looks like this should be solved once this is merged https://github.com/SciML/RecursiveArrayTools.jl/pull/139. No need to introduce anything to StructArrays or ArrayInterface, as this fix should be covered by the default behavior.

**Closed** 2021-04-25 22:04 UTC
